In [9]:
import yfinance as yf
import pandas as pd
import numpy as np

gme = yf.Ticker("GME")
gme_hour = gme.history(start="2021-01-25", end="2021-01-27", interval = '1h')
gme_day = gme.history(period = '2mo', interval = '1d')

In [10]:
gme_hour
# gme_day

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-01-25,96.730003,120.000000,85.000000,119.919998,50748185,0,0
2021-01-25,119.959999,159.179993,85.389999,94.779999,38900598,0,0
2021-01-25,96.000000,107.309998,61.130001,72.709999,21449403,0,0
2021-01-25,76.339996,85.800003,65.370003,69.319901,22096843,0,0
2021-01-25,68.980003,86.540001,67.900002,82.199997,19369689,0,0
2021-01-25,82.120102,84.499901,71.100098,78.989998,15002353,0,0
2021-01-25,78.989998,81.250000,75.510002,76.764999,7444286,0,0
2021-01-26,95.000000,101.620003,81.110001,82.599998,25291542,0,0
2021-01-26,82.380096,94.000000,80.199997,87.429901,14031735,0,0
2021-01-26,87.419899,93.000000,85.540001,92.523003,7118369,0,0
2021-01-26,92.510002,114.239998,92.430099,112.010002,30146487,0,0
2021-01-26,112.233398,125.000000,106.000000,122.190002,31784649,0,0
2021-01-26,122.369904,149.250000,117.199997,148.389999,38074022,0,0
2021-01-26,148.311798,150.000000,132.309998,145.964996,14015666,0,0

In [3]:
gme_hour
gme_day

x1 = gme_hour['Date']
y1 = gme_hour['Close']

x2 = gme_day['Date']
y2 = gme_day['Close']

fig, ax = plt.subplots(2, figsize = (9,9))
ax[0].plot(x1,y1, color = 'purple')
ax[0].set_title('GME Hourly Prices')
ax[0].set_xlabel('Hours')
ax[0].set_ylabel('Price')

ax[1].plot(x2,y2, color = 'red')
ax[1].set_title('GME Daily Prices')
ax[1].set_xlabel('Days')
ax[1].set_ylabel('Price')

KeyError: 'Date'

                  Open        High  ...  Dividends  Stock Splits
Date                                ...
2020-12-22   16.219999   20.040001  ...          0             0
2020-12-23   20.170000   22.350000  ...          0             0
2020-12-24   21.010000   21.480000  ...          0             0
2020-12-28   21.309999   21.969999  ...          0             0
2020-12-29   20.820000   21.070000  ...          0             0
2020-12-30   19.379999   20.000000  ...          0             0
2020-12-31   19.250000   19.799999  ...          0             0
2021-01-04   19.000000   19.100000  ...          0             0
2021-01-05   17.350000   18.080000  ...          0             0
2021-01-06   17.340000   18.980000  ...          0             0
2021-01-07   18.469999   19.450001  ...          0             0
2021-01-08   18.180000   18.299999  ...          0             0
2021-01-11   19.410000   20.650000  ...          0             0
2021-01-12   19.959999   20.400000  ...          0             0
2021-01-13   20.420000   38.650002  ...          0             0
2021-01-14   38.090000   43.060001  ...          0             0
2021-01-15   38.490002   40.750000  ...          0             0
2021-01-19   41.549999   45.520000  ...          0             0
2021-01-20   37.369999   41.189999  ...          0             0
2021-01-21   39.230000   44.750000  ...          0             0
2021-01-22   42.590000   76.760002  ...          0             0
2021-01-25   96.730003  159.179993  ...          0             0
2021-01-26   88.559998  150.000000  ...          0             0
2021-01-27  354.829987  380.000000  ...          0             0
2021-01-28  265.000000  483.000000  ...          0             0
2021-01-29  379.709991  413.980011  ...          0             0
2021-02-01  316.559998  322.000000  ...          0             0
2021-02-02  140.759995  158.000000  ...          0             0
2021-02-03  112.010002  113.400002  ...          0             0
2021-02-04   91.190002   91.500000  ...          0             0
2021-02-05   54.040001   95.000000  ...          0             0
2021-02-08   72.410004   72.660004  ...          0             0
2021-02-09   56.610001   57.000000  ...          0             0
2021-02-10   50.770000   62.830002  ...          0             0
2021-02-11   50.009998   55.320000  ...          0             0
2021-02-12   50.750000   55.240002  ...          0             0
2021-02-16   52.660000   53.500000  ...          0             0
2021-02-17   49.770000   51.189999  ...          0             0
2021-02-18   48.490002   48.869999  ...          0             0
2021-02-19   41.279999   43.889999  ...          0             0
2021-02-22   46.689999   48.509998  ...          0             0

[41 rows x 7 columns]